### ISSUE TITLE
Animation not triggered when coming back from a navigation

### ISSUE THREAD

**Issue by ederjavs** [FilledStacks/smart_flare#2]
following the example everything works correctly but when a push page is incovated from the active area and then it becomes pop the on tap function is executed from the central icon but it does not perform the animation

the following message also appears:

I/flutter (24452): SmartFlare:Warning - If you are cycling through animations there's a high chance that you might need to set the animationRequired property on the Active area.

```dart
class _State extends State<ListVisitas> {
  
  var animationWidth = 195.0;
  var animationHeight = 151.0;

 
  @override
  Widget build(BuildContext context) {
    var activeAreas = [
      // Insert top-left
      ActiveArea(
          debugArea: true,
          area: Rect.fromLTWH(40, 20, 50, 40),
          
          animationName: 'image_tapped',
          onAreaTapped: () {
            Navigator.push(
              context,
              ScaleRoute(widget: Package()),
            );
          }),
      // Insert middle

      // Insert top-right
      ActiveArea(
          debugArea: true,
          area: Rect.fromLTWH(110, 20, 50, 40),
          
          animationName: 'image_tapped',
          onAreaTapped: () {
            Navigator.push(
              context,
              ScaleRoute(widget: PackageOther()),
            );
          }),
      // Insert bottom half area
      ActiveArea(
          debugArea: true,
          area: Rect.fromLTWH(75, 82, 50, 55),
          animationsToCycle: ['deactivate', 'activate'],
          onAreaTapped: () {
            print('Activate toggles!');
          }),
    ];

    return SafeArea(
      top: false,
      bottom: false,
      child: new Container(
        child: new Stack(
          alignment: Alignment.topLeft,
          children: <Widget>[
            Padding(
                child: ExpandItems(),
                padding: const EdgeInsets.only(top: 60.0)),
            
            GuillotineMenu(),
            Align(
                alignment: Alignment.bottomCenter,
                child: SmartFlareActor(
                  width: animationWidth,
                  height: animationHeight,
                  filename: 'assets/animate/buttoms.flr',
                  startingAnimation: 'deactivate',
                  activeAreas: activeAreas,
                )),
          ],
        ),
      ),
    );
  }
}
```

**Comment by FilledStacks** [comment]
> following the example everything works correctly but when a push page is incovated from the active area and then it becomes pop

I don't know exactly what this means but I think you're saying when you navigate away from the page and come back the animations don't play anymore?

> the following message also appears: I/flutter (24452): SmartFlare:Warning -

Yes, this was something I left during initial development. I put the wrong property name in there. Will fix that warning and push it up now.

**Comment by FilledStacks** [comment]
I have confirmed that coming back from a navigation is causing the animations not to play properly. I'll make an update when I figured it out. If you find anything please let me know to speed up the process.

**Comment by FilledStacks** [comment]
Fixed up the bug. I was storing the FlareController in the StatefullWidget class instead of the State<> class so I think it was getting stale on navigation [See commit](https://github.com/FilledStacks/smart_flare/commit/a23c71ce39bf6628e6286d27b6df674e721a4807) . I also added a new parameter to the SmartFlareActor called playStartingAnimationWhenRebuilt. When that's set to true it will play the starting animation when you navigate back to the view with your animation on. [See code](https://github.com/FilledStacks/smart_flare/commit/8a07b9a70d6b683a207dd57ca5b4869d4d8a94f4)

I used [your code in the example ](https://github.com/FilledStacks/smart_flare/commit/17c544227842777fef0fb4cffc15b023d62c1acc)file called navigation_demo.dart so you can check it out. Animations play fine when navigating back to it. 

Thanks for filing this issue, it actually brought in some good changes to the package. Version 0.2.6 is published.
